x-shared-env: &shared-api-worker-env
      PORT: ${PORT:-3000}
      NODE_ENV: ${WORKER_PORT:-production}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:-}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL:-/auth/sign-in}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL:-/auth/sign-up}
      DATABASE_URL: ${DATABASE_URL:-}

services:
  # server:
  #   image: ivannguyendev/aisuckhoe-webchat:main
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=${NODE_ENV:-production}
  #     - PORT=${PORT:-3000}
  #     - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
  #     - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-}
  #     - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL:-/auth/sign-in}
  #     - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL:-/auth/sign-up}
  #     - DATABASE_URL=${DATABASE_URL:-}
  #   command: sh -c "HOSTNAME='0.0.0.0' node server.js"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped