x-shared-env: &shared-api-worker-env
      PORT: ${PORT:-3000}
      NODE_ENV: ${WORKER_PORT:-production}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:-}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL:-/auth/sign-in}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL:-/auth/sign-up}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-https://hoi.aisuckhoe.com}
      POSTGRESQL_URL: ${POSTGRESQL_URL:-postgresql://postgres:postgres@localhost:5432/aisuckhoe}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:-}
      NEXT_PUBLIC_CLOUDINARY_API_KEY: ${NEXT_PUBLIC_CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
      FIREBASE_ADMIN_CERT_PATH: ${FIREBASE_ADMIN_CERT_PATH:-/opt/serviceAccountKey.json}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY:-}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:-}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID:-}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:-}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID:-}
      FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${FIREBASE_SERVICE_ACCOUNT_KEY_JSON:-}
      REDIS_URL: ${REDIS_URL:-rediss://username:password@localhost:21079}

services:
  server:
    image: ivannguyendev/aisuckhoe-webchat:main
    ports:
      - "3000:3000"
    environment:
      <<: *shared-api-worker-env
      # Example: NODE_ENV: ${NODE_ENV:-development}
    command: sh -c "echo \"$$FIREBASE_SERVICE_ACCOUNT_KEY_JSON\" > /opt/serviceAccountKey.json && HOSTNAME='0.0.0.0' node server.js"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
