export const relationships = {
  father: "father",
  mother: "mother",
  brother: "brother",
  sister: "sister",
  son: "son",
  daughter: "daughter",
  paternal_grandfather: "paternal_grandfather",
  paternal_grandmother: "paternal_grandmother",
  maternal_grandfather: "maternal_grandfather",
  maternal_grandmother: "maternal_grandmother",
  paternal_uncle: "paternal_uncle",
  paternal_aunt: "paternal_aunt",
  maternal_uncle: "maternal_uncle",
  maternal_aunt: "maternal_aunt",
  male_cousin: "male_cousin",
  female_cousin: "female_cousin",
  great_grandfather: "great_grandfather",
  great_grandmother: "great_grandmother",
  great_grandchild: "great_grandchild",
  great_great_grandchild: "great_great_grandchild",
  father_in_law_husband: "father_in_law_husband",
  mother_in_law_husband: "mother_in_law_husband",
  father_in_law_wife: "father_in_law_wife",
  mother_in_law_wife: "mother_in_law_wife",
  brother_in_law_sister_husband: "brother_in_law_sister_husband",
  sister_in_law_brother_wife: "sister_in_law_brother_wife",
  daughter_in_law: "daughter_in_law",
  son_in_law: "son_in_law",
  stepfather: "stepfather",
  stepmother: "stepmother",
  stepchild: "stepchild",
  half_brother: "half_brother",
  half_sister: "half_sister",
} as const;

export const genders = {
  male: "male",
  female: "female",
} as const;
