export const relationships = {
  father: "Cha/Bố/Ba",
  mother: "Mẹ/Má",
  older_brother: "Anh trai",
  younger_brother: "Em trai",
  older_sister: "Chị gái",
  younger_sister: "Em gái",
  son: "Con trai",
  daughter: "Con gái",
  paternal_grandfather: "Ông nội",
  paternal_grandmother: "Bà nội",
  maternal_grandfather: "Ông ngoại",
  maternal_grandmother: "Bà ngoại",
  older_paternal_uncle: "Bác trai",
  younger_paternal_uncle: "Chú",
  older_paternal_aunt: "Bác gái",
  paternal_aunt: "Cô",
  maternal_uncle: "Cậu",
  maternal_aunt: "Dì",
  older_male_cousin: "Anh họ",
  older_female_cousin: "Chị họ",
  younger_male_cousin: "Em họ",
  younger_female_cousin: "Em họ",
  great_grandfather: "Ông cố (Ông sơ)",
  great_grandmother: "Bà cố (Bà sơ)",
  great_grandchild: "Chắt",
  great_great_grandchild: "Chút",
  father_in_law_husband: "Bố chồng",
  mother_in_law_husband: "Mẹ chồng",
  father_in_law_wife: "Bố vợ",
  mother_in_law_wife: "Mẹ vợ",
  brother_in_law_sister_husband: "Anh rể",
  brother_in_law_younger_sister_husband: "Em rể",
  sister_in_law_older_brother_wife: "Chị dâu",
  sister_in_law_younger_brother_wife: "Em dâu",
  daughter_in_law: "Con dâu",
  son_in_law: "Con rể",
  stepfather: "Cha dượng",
  stepmother: "Mẹ kế",
  stepchild: "Con riêng",
  half_brother: "Anh em cùng cha khác mẹ / cùng mẹ khác cha",
  half_sister: "Chị em cùng cha khác mẹ / cùng mẹ khác cha",
};
